[0m12:56:12.526286 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A62C1E5E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A62C0F2510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A62C6C2570>]}


============================== 12:56:12.533320 | bb6fc5db-1d05-485a-809b-7276c3de7c4d ==============================
[0m12:56:12.533320 [info ] [MainThread]: Running with dbt=1.9.6
[0m12:56:12.535462 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\braah\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:56:12.537001 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\braah\OneDrive\Desktop\exo_hzm\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:56:12.540700 [debug] [MainThread]: Command `dbt run` failed at 12:56:12.540700 after 0.19 seconds
[0m12:56:12.541744 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A62EC692B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A62F1B80B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A62F1B81A0>]}
[0m12:56:12.542678 [debug] [MainThread]: Flushing usage events
[0m12:56:12.957727 [debug] [MainThread]: An error was encountered while trying to flush usage events
